import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-tiendas-screen',
  templateUrl: './tiendas-screen.component.html',
  styleUrls: ['./tiendas-screen.component.scss']
})
export class TiendasScreenComponent implements OnInit{
  constructor(){}
  ngOnInit(): void {}

  public tiendas: string[]= [
    "L CENTRO", "L INSURGENTES", "L POLANCO", "L SATELITE", "L PERISUR",
    "L COAPA", "L SANTA FE", "L XALAPA PLAZA CRYSTAL", "L CORDOBA PLAZA CRYSTAL", "L VILLAHERMOSA CRYSTAL",
    "L TUXTLA GTZ", "L PUEBLA CRYSTAL", "L COATZACOALCOS PLAZA CRYSTAL", "L POZA RICA PLAZA CRYSTAL", "L TAPACHULA",
    "L VILLAHERMOSA", "L MTY CENTRO", "L GRAN PLAZA", "L ACAPULCO GALERIAS", "L VERACRUZ MOCAMBO",
    "L PERINORTE", "L MONTERREY", "L CHIHUAHUA PRESIDENTES", "L SAN LUIS POTOSI EL DORADO", "L OAXACA",
    "L TAMPICO", "L CHIHUAHUA", "L TORREON", "L QUERETARO", "L MTY VALLE",
    "L CULIACAN", "L IRAPUATO", "L PACHUCA", "L HERMOSILLO ENCINAS", "L GUADALAJARA CENTRO",
    "L PLAZA PATRIA", "L TEPIC CENTRO", "L MAZATLÁN CENTRO", "L MORELIA", "L AGUASCALIENTES VILLASUNCIÓN",
    "L CIUDAD OBREGON", "L PASEO MORELIA", "L PUERTO VALLARTA", "L ZAPOPAN", "L SALTILLO",
    "L TLAQUEPAQUE", "L LEON", "L PUEBLA", "L VERACRUZ", "L METEPEC", "L CANCUN",
    "L MERIDA", "L CUERNAVACA", "L GUADALAJARA", "L CHETUMAL", "L ECATEPEC",
    "L PARQUE DELTA", "L XALAPA", "L LINDAVISTA", "L COLIMA", "L COATZACOALCOS",
    "L AGUASCALIENTES", "L TEZONTLE", "L TEPIC", "L DURANGO", "L CAMPECHE",
    "L INTERLOMAS", "L ATIZAPAN", "L CELAYA", "L PUEBLA SERDAN", "L CD JUAREZ",
    "L MTY CUMBRES", "L MAZATLAN", "L ORIZABA", "CD IZCALLI", "L CIUDAD VICTORIA",
    "L ZACATECAS", "L VILLAHERMOSA ALTABRISA", "L GUADALAJARA OBLATOS", "L SAN LUIS", "L TOLUCA",
    "L VERACRUZ EL DORADO", "L LEON ALTACIA", "L SANTA ANITA", "L TUXPAN", "L CD JARDIN",
    "L QUERETARO ANTEA", "L TAMPICO ALTAMA", "L TLAXCALA", "L ZAMORA", "L COACALCO",
    "L TLALNEPANTLA", "L MONTERREY LA FE", "L TUXTLA ORIENTE", "L CUAUTLA", "L SALAMANCA",
    "L TECAMAC", "L TOREO", "L LA ISLA", "L TEHUACAN", "L SAN MIGUEL DE ALLENDE",
    "L CHILPANCINGO", "L CIUDAD DEL CARMEN", "L LOS MOCHIS", "L ACAPULCO", "L PLAYA DEL CARMEN",
    "L LA PAZ", "L ISTMO", "L SAN JUAN DEL RIO", "L MEXICALI", "L PARQUE PUEBLA",
    "L HERMOSILLO GALERIAS MALL", "L GUANAJUATO", "L PASEO QUERÉTARO", "L PARQUE LAS ANTENAS", "L MONTERREY ESFERA",
    "L MERIDA CABO NORTE", "L OAXACA PLAZA BELLA", "L MONCLOVA", "L PUEBLA ATLIXCO LA MORELADA",
    "L FRESNILLO", "L COMITAN", "L ZAPOPAN LA PERLA", "L TIJUANA", "L MITIKAH"];

  public isMobile(){
    if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini|Mobile|mobile|CriOS/i.test(navigator.userAgent)){
      return "interior-mobile";
    }else{
      return "interior-normal";
    }
  }
}
